add some missing HALS to FCM
* Reason

ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.xiaomi.sensor.camera.IMiCam/default (@1)
    xiaomi.system.hypsys.common.IHypSysSsi/default (@1)
    xiaomi.system.hypsys.common.IHypSysSsiIntl/default (@1)